using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BusinessErrorGenerator
{
    [Generator]
    public class BusinessErrorExceptionGenerator : IIncrementalGenerator
    {
        private static readonly DiagnosticDescriptor DuplicateError = new DiagnosticDescriptor(
            id: "BEEG001",
            title: "Código de erro duplicado",
            messageFormat: "O Código de erro '{0}' está duplicado",
            category: "BusinessErrorExceptionGenerador",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var fieldData = context.SyntaxProvider
                .CreateSyntaxProvider(
                predicate: (s, _) =>
                {
                    if (s is FieldDeclarationSyntax field)
                    {
                        if (field.Parent is ClassDeclarationSyntax)
                        {
                            return field.Modifiers.Any(f => f.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.StaticKeyword));
                        }
                    }
                    return false;
                },
                transform: (ctx, _) =>
                {
                    var compilation = ctx.SemanticModel.Compilation;
                    var errorAttributeSymbol = compilation.GetTypeByMetadataName("BusinessErrorShared.Attributes.ErrorAttribute");

                    var fieldDeclaration = (FieldDeclarationSyntax)ctx.Node;
                    var fieldSymbol = ctx.SemanticModel.GetDeclaredSymbol(fieldDeclaration.Declaration.Variables.First()) as IFieldSymbol;

                    if (fieldSymbol is null || errorAttributeSymbol is null)
                        return null;

                    var attributeData = fieldSymbol.GetAttributes()
                        .FirstOrDefault(att => SymbolEqualityComparer.Default.Equals(att.AttributeClass, errorAttributeSymbol));

                    if (attributeData is null)
                        return null;

                    var message = attributeData.ConstructorArguments.FirstOrDefault().Value?.ToString();

                    if (string.IsNullOrEmpty(message))
                        return null;

                    return new
                    {
                        ErrorCodeName = fieldSymbol.Name,
                        ErrorMessage = message,
                        Location = fieldSymbol.Locations.FirstOrDefault()
                    };
                })
                .Where(csp => csp != null)
                .Collect();

            context.RegisterSourceOutput(fieldData, (sourceContext, errors) =>
            {
                if (errors.IsDefaultOrEmpty)
                    return;

                var uniqueCodes = new HashSet<string>();

                foreach (var error in errors)
                {
                    if (!uniqueCodes.Add(error.ErrorCodeName))
                    {
                        sourceContext.ReportDiagnostic(
                            Diagnostic.Create(
                                DuplicateError,
                                error.Location,
                                error.ErrorCodeName));

                        return;
                    }
                }

                var businessErrors = new StringBuilder();

                businessErrors.AppendLine("// <auto-generated/>");
                businessErrors.AppendLine("#nullable enable");
                businessErrors.AppendLine();

                businessErrors.AppendLine("namespace BusinessErrorGenerator");
                businessErrors.AppendLine("{");

                businessErrors.AppendLine("   public static partial class BusinessErrors");
                businessErrors.AppendLine("   {");

                businessErrors.AppendLine("        private static readonly System.Collections.Generic.Dictionary<string, string> _errorMessages = new()");
                businessErrors.AppendLine("        {");
                foreach (var error in errors)
                {
                    var escapedMessage = error.ErrorMessage
                        .Replace("\\", "\\\\")
                        .Replace("\"", "\\\"");

                    businessErrors.AppendLine($"            {{ \"{error.ErrorCodeName}\", \"{escapedMessage}\" }},");
                }
                businessErrors.AppendLine("        };");
                businessErrors.AppendLine();

                businessErrors.AppendLine("        public static string GetMessage(string errorCode)");
                businessErrors.AppendLine("        {");
                businessErrors.AppendLine("            if (_errorMessages.TryGetValue(errorCode, out var message))");
                businessErrors.AppendLine("            {");
                businessErrors.AppendLine("                return message;");
                businessErrors.AppendLine("            }");
                businessErrors.AppendLine();
                businessErrors.AppendLine("            return $\"Erro desconhecido: {errorCode}\";");
                businessErrors.AppendLine("        }");

                businessErrors.AppendLine("    }");
                businessErrors.AppendLine("}");

                sourceContext.AddSource("BusinessErrors.g.cs", SourceText.From(businessErrors.ToString(), Encoding.UTF8));

                var generatedErrorMessageProvider = new StringBuilder();

                generatedErrorMessageProvider.AppendLine("// <auto-generated/>");
                generatedErrorMessageProvider.AppendLine("#nullable enable");
                generatedErrorMessageProvider.AppendLine();

                generatedErrorMessageProvider.AppendLine("using BusinessErrorShared.Interfaces;");
                generatedErrorMessageProvider.AppendLine();

                generatedErrorMessageProvider.AppendLine("namespace BusinessErrorGenerator");
                generatedErrorMessageProvider.AppendLine("{");

                generatedErrorMessageProvider.AppendLine("    public class GeneratedErrorMessageProvider : IErrorMessageProvider");
                generatedErrorMessageProvider.AppendLine("    {");
                generatedErrorMessageProvider.AppendLine("        public string GetMessage(string errorCode)");
                generatedErrorMessageProvider.AppendLine("        {");
                generatedErrorMessageProvider.AppendLine("            return BusinessErrors.GetMessage(errorCode);");
                generatedErrorMessageProvider.AppendLine("        }");
                generatedErrorMessageProvider.AppendLine("    }");

                generatedErrorMessageProvider.AppendLine("}");

                sourceContext.AddSource("GeneratedErrorMessageProvider.g.cs", SourceText.From(generatedErrorMessageProvider.ToString(), Encoding.UTF8));
            });
        }
    }
}